application: beevote
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /
  script: index.app

- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"