application: beevote
version: 5
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  script: admin.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"